# Generated by Django 3.2.7 on 2021-09-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nieznany'), (1, 'Fantasy'), (2, 'Horror'), (3, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='biblioteka.autor'),
        ),
    ]
